- hosts: localhost
  connection: local
  vars:
    pull_user: ansible

  roles:
    - role: user
      vars:
        user: "{{ pull_user }}"
        system_user: yes

  tasks:
    - include: ansible-pull-cron.yml
      vars:
        user: "{{ pull_user }}"

    - name: Install packages
      become: yes
      yum: 
        name: 
          - httpd
          - wget
          - htop
      tags:
        - httpd
        
    - name: httpd restart
      become: yes
      systemd:
        name: httpd
        state: restarted
      tags:
        - httpd



    - name: Install db
      become: yes
      yum: 
        name: tomcat
      tags:
        - tomcat
    - name: tomcat restart
      become: yes
      systemd:
        name: tomcat
        state: restarted
      tags:
        - tomcat
