- hosts: localhost
  connection: local
  # vars:
  #   pull_user: ansible

  # roles:
  #   - role: user
  #     vars:
  #       user: "{{ pull_user }}"
  #       system_user: yes

  tasks:
    # - include: ansible-pull-cron.yml
    #   vars:
    #     user: "{{ pull_user }}"

    - name: Install httpd
      become: yes
      yum: 
        name: httpd
      tags:
        - httpd

    - name: Change index page
      become: yes
      copy:
        src: index.html
        dest: /var/www/html/index.html
      notify: httpd restart
      tags:
        - httpd
        
    - name: check httpd start and enabled
      become: yes
      systemd:
        name: httpd
        state: started
        enabled: yes
      tags:
        - httpd



    - name: Install tomcat
      become: yes
      yum: 
        name: 
        - tomcat
        - tomcat-webapps
        - tomcat-admin-webapps     
      tags:
        - tomcat 

    - name: Change tomcat-users.xml 
      become: yes
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat/tomcat-users.xml 
      notify: tomcat restart
      tags:
        - tomcat

    # - name: Deploy clusterjsp on tomcat
    #   become: yes
    #   copy:
    #     src: clusterjsp.war
    #     dest: /usr/share/tomcat/webapps/clusterjsp.war
    #   tags:
    #     - tomcat
    

    - name: check tomcat started and enabled
      become: yes
      systemd:
        name: tomcat
        state: started
        enabled: yes
      tags:
        - tomcat

  handlers:
    - name: httpd restart
      systemd:
        name: httpd
        state: restarted
    - name: tomcat restart
      systemd:
        name: tomcat
        state: restarted

